export const mockedItems: CreatePurchaseItemWithName[] = [
  {
    itemId: "item001",
    name: "Apples",
    quantityInHundreds: 10,
    pricePerUnit: 1.2,
    totalPrice: 120,
  },
  {
    itemId: "item002",
    name: "Oranges",
    quantityInHundreds: 5,
    pricePerUnit: 1.5,
    totalPrice: 75,
  },
  {
    itemId: "item003",
    name: "Bananas",
    quantityInHundreds: 8,
    pricePerUnit: 0.9,
    totalPrice: 72,
  },
  {
    itemId: "item004",
    name: "Tomatoes",
    quantityInHundreds: 12,
    pricePerUnit: 1.1,
    totalPrice: 132,
  },
  {
    itemId: "item005",
    name: "Potatoes",
    quantityInHundreds: 15,
    pricePerUnit: 0.6,
    totalPrice: 90,
  },
  {
    itemId: "item006",
    name: "Onions",
    quantityInHundreds: 9,
    pricePerUnit: 0.8,
    totalPrice: 72,
  },
  {
    itemId: "item007",
    name: "Carrots",
    quantityInHundreds: 11,
    pricePerUnit: 1.0,
    totalPrice: 110,
  },
  {
    itemId: "item008",
    name: "Cabbages",
    quantityInHundreds: 4,
    pricePerUnit: 1.3,
    totalPrice: 52,
  },
  {
    itemId: "item009",
    name: "Spinach",
    quantityInHundreds: 6,
    pricePerUnit: 0.7,
    totalPrice: 42,
  },
  {
    itemId: "item010",
    name: "Lettuce",
    quantityInHundreds: 7,
    pricePerUnit: 1.1,
    totalPrice: 77,
  },
  {
    itemId: "item011",
    name: "Peppers",
    quantityInHundreds: 6,
    pricePerUnit: 2.0,
    totalPrice: 120,
  },
  {
    itemId: "item012",
    name: "Cucumbers",
    quantityInHundreds: 10,
    pricePerUnit: 0.9,
    totalPrice: 90,
  },
  {
    itemId: "item013",
    name: "Zucchini",
    quantityInHundreds: 5,
    pricePerUnit: 1.4,
    totalPrice: 70,
  },
  {
    itemId: "item014",
    name: "Eggplants",
    quantityInHundreds: 8,
    pricePerUnit: 1.2,
    totalPrice: 96,
  },
  {
    itemId: "item015",
    name: "Broccoli",
    quantityInHundreds: 6,
    pricePerUnit: 1.8,
    totalPrice: 108,
  },
  {
    itemId: "item016",
    name: "Cauliflower",
    quantityInHundreds: 5,
    pricePerUnit: 1.7,
    totalPrice: 85,
  },
  {
    itemId: "item017",
    name: "Sweet Corn",
    quantityInHundreds: 9,
    pricePerUnit: 1.0,
    totalPrice: 90,
  },
  {
    itemId: "item018",
    name: "Pumpkin",
    quantityInHundreds: 4,
    pricePerUnit: 2.5,
    totalPrice: 100,
  },
  {
    itemId: "item019",
    name: "Radish",
    quantityInHundreds: 7,
    pricePerUnit: 0.9,
    totalPrice: 63,
  },
  {
    itemId: "item020",
    name: "Beets",
    quantityInHundreds: 5,
    pricePerUnit: 1.3,
    totalPrice: 65,
  },
  {
    itemId: "item021",
    name: "Garlic",
    quantityInHundreds: 3,
    pricePerUnit: 2.2,
    totalPrice: 66,
  },
  {
    itemId: "item022",
    name: "Ginger",
    quantityInHundreds: 2,
    pricePerUnit: 3.0,
    totalPrice: 60,
  },
  {
    itemId: "item023",
    name: "Chili",
    quantityInHundreds: 4,
    pricePerUnit: 2.0,
    totalPrice: 80,
  },
  {
    itemId: "item024",
    name: "Turmeric",
    quantityInHundreds: 3,
    pricePerUnit: 2.5,
    totalPrice: 75,
  },
  {
    itemId: "item025",
    name: "Mangoes",
    quantityInHundreds: 6,
    pricePerUnit: 2.0,
    totalPrice: 120,
  },
  {
    itemId: "item026",
    name: "Papayas",
    quantityInHundreds: 5,
    pricePerUnit: 1.8,
    totalPrice: 90,
  },
  {
    itemId: "item027",
    name: "Guavas",
    quantityInHundreds: 4,
    pricePerUnit: 1.5,
    totalPrice: 60,
  },
  {
    itemId: "item028",
    name: "Pineapples",
    quantityInHundreds: 3,
    pricePerUnit: 2.5,
    totalPrice: 75,
  },
  {
    itemId: "item029",
    name: "Watermelons",
    quantityInHundreds: 2,
    pricePerUnit: 4.0,
    totalPrice: 80,
  },
  {
    itemId: "item030",
    name: "Melons",
    quantityInHundreds: 3,
    pricePerUnit: 3.5,
    totalPrice: 105,
  },
];
